name: Build

on:

  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      plugin_name:
        description: 'Plugin name'
        required: true

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v3

      - name: Integrate the plugin in the template
        run: |
          rm -rf .github 
          rm README.md
          git clone https://github.com/barthofu/tscord
          mv tscord/* ./
          rm -rf tscord
          mkdir -p src/plugins
          mv plugins/${{github.event.inputs.plugin_name}} src/plugins/${{github.event.inputs.plugin_name}}
          rm -rf plugins

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17.6.0
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build